name: CI

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make test

  build:
    runs-on: ubuntu-latest
    needs: test 
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23' 

      - name: Build for Linux AMD64
        run: |
          mkdir -p build
          output_dir="build/${{ github.ref_name }}_linux_amd64"
          mkdir -p "$output_dir"
          GOOS=linux GOARCH=amd64 go build -o "$output_dir/url_shortener" .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
